version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www # ローカルをコンテナ内にマウント
    command: bash -c "cd ./src && npm install next && npm run dev"
    ports:
      - "3000:3000"
    stdin_open: true